#!/bin/sh
ssh -o StrictHostKeyChecking=no -i /var/lib/jenkins/workspace/SSH/MyWebServerKeyPair.pem ec2-user@52.65.13.26 <<EOF        
 sudo su
 cd /var/www/yelpCampApp
 git pull
 npm install
 echo 'Stopping Forever old process'
 forever stop app.js
 echo 'Starting forever new process'
 BUILD_ID=dontKillMe forever -a -l myapp.log app.js &
 echo 'Done. Exiting...'
 exit 0
EOF