#!/bin/sh     
sudo su
ssh -i /home/ec2-user/SSH/MyWebServerKeyPair.pem ec2-user@52.65.13.26 <<EOF        
 sudo su
 cd /var/www/yelpCampApp
 git pull
 npm install       
 node app.js
 exit       
EOF